# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1ef300f347365d8293e2137d43b111b8"
name = "greenex-dev-1"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/order-create"

  [[webhooks.subscriptions]]
  topics = [ "orders/updated" ]
  uri = "/webhooks/order-update"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/product-update"

  [[webhooks.subscriptions]]
  topics = [ "customers/create" ]
  uri = "/webhooks/customer-create"

  [[webhooks.subscriptions]]
  topics = [ "fulfillments/create" ]
  uri = "/webhooks/fulfillment-create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
