# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "266215804456f604c85376137bbfa4d7"
name = "GreenExApp"
application_url = "https://greenexapp.pixeltechnosol.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_locations,read_orders,write_assigned_fulfillment_orders,write_orders"

[auth]
redirect_urls = [ "https://greenexapp.pixeltechnosol.com/authenticate" ]
